### ISSUE TITLE
Addressation system: OctTree or SlippyMap

### ISSUE THREAD

**Issue by martinheidegger** [pnext/pnext-io#12]
The Potree format uses a [OctTree notation format](https://github.com/potree/potree/blob/develop/docs/potree-file-format.md#index-files) for addressing nodes.
The new [EPT format](https://github.com/connormanning/ept) [uses](https://github.com/connormanning/ept#point-cloud-data) a [SlippyMap](https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames) addressation system.

It should be no problem to convert between the two but it is a question on what side of the process that should be used and which format is more sensible.

The [API](https://github.com/pnext/pnext-io/blob/master/spec/Node.proto#L3) also (also the [new API](https://github.com/pnext/pnext-io/blob/958ecf5d8f3f3054659cdb6c73b7e6adb184734a/spec/Node.proto#L4)) specifies an addressation system and it is an OctTree. Should this change? Is it better for the API to expose a SlippyMap notation system.

**Comment by dkastl** [comment]
There was a response by Connor to "Why a new system?"
https://lists.osgeo.org/pipermail/pdal/2018-July/001613.html

```
This choice was made because to access the new static EPT format, you must
use DXYZ keying to read the data files.  Therefore it seemed fitting to
match the hierarchy notation to the data storage notation.  Also, with the
new data keying format being a slippy-map tiling, it seemed sensible to
avoid mixing it with the old octree-node relative addressing.

Comments/criticisms on the format in general are welcome - and feel free to
submit issues on that `ept` repository in that regard.
```

Thoughts?

**Comment by dkastl** [comment]
@martinheidegger , what do you mean with "which format is more sensible"?

My personal opinion is, that the SlippyMap system might look more familiar to many in the community. It's something a lot of people are used to. If there are no technical issues or disadvantages of one or the other, then the SlippyMap way of doing it looks better to me.

However, if this is either causing a lot of extra work to change with pnext-io and could be also changed at a later time, maybe we could just leave this for later.

**Comment by martinheidegger** [comment]
> This choice was made because to access the new static EPT format, you must
use DXYZ keying to read the data files. 

"must" is the keyword for this issue. I have problems to understand: What makes this a must?

> Therefore it seemed fitting to match the hierarchy notation to the data storage notation.  Also, with the new data keying format being a slippy-map tiling, it seemed sensible to avoid mixing it with the old octree-node relative addressing.

Naturally you want to reduce friction between the addressation by using the same system in all contexts. This is the same argument for the Octree system used in Potree: Because that is how potree internally stores/uses nodes (0-7 for each child). Maybe its possible to use SlippyMap as an internal format in the viewer too but it might require major rewrites in the internas of the renderer.

> SlippyMap system might look more familiar to many in the community. 

Yes, and it has other advantages, such as a static size: always 4 uint16 numbers vs. a variable length uint8 array. It might even be better for things such as querying or update-event-information (if child nodes change); but I havn't tried that yet.

> Comments/criticisms on the format in general are welcome - and feel free to submit issues on that `ept` repository in that regard.

After researching this I really am stuck with "I dont know which is better"; Which is why I refrained from commenting. I couldn't argue for either way properly. Its a fringe issue...

> However, if this is either causing a lot of extra work to change with pnext-io and could be also changed at a later time, maybe we could just leave this for later.

In order [to implement an EPT reader](https://github.com/pnext/pnext-io/issues/11) we need [a properly working Octree <-> SlippyMap converter](https://github.com/orgs/pnext/projects/1#card-11204535) which is "extra-work" that would be avoided if it was just a OctTree addressation. _(Note: it could be as simple as writing tests to [my gist](https://gist.github.com/martinheidegger/aad4c5be73a949dc0df7afe190d4fc19))_

**Comment by dkastl** [comment]
Just curious how Potree solves this. Doesn't add Markus support for the EPT format? Then he must have the same questions.

**Comment by martinheidegger** [comment]
To my knowledge connor adds it.

**Comment by connormanning** [comment]
The relevant potree code is [here](https://github.com/connormanning/potree/blob/ept/src/PointCloudEptGeometry.js#L258-L274), where the EPT DXYZ keys are converted to Potree's keys.  This isn't strictly necessary since it's a completely different loader that doesn't need to work the same way, but there are some unrelated aspects of potree that inspect the keys.  This conversion could potentially be entirely removed from Potree.  This is my fork of Potree that [potree.entwine.io](http://potree.entwine.io) is running, which will be pull-requested to Potree itself soon enough.

> ...to access the new static EPT format, you must use DXYZ keying to read the data files.

> "must" is the keyword for this issue. I have problems to understand: What makes this a must?

This is a "must" simply because the EPT format is statically arranged as DXYZ, so for a client to be accessing EPT, it must be using DXYZ filenames because that is what exists in the EPT output.  I do not mean "must" as in "EPT *must* work this way and could not theoretically use octree traversal storage" - I just mean that *because* EPT already uses DXYZ, clients accessing it directly must also understand DXYZ.

DXYZ was chosen for the EPT data files (and therefore the corresponding hierarchy) primarily because it seemed a more apt analog to raster land, where I get the impression that slippy-map schemes are much more common than octree schemes in existing APIs.

**Comment by dkastl** [comment]
Thanks a lot @connormanning for your explanations!

As I commented before, I also think, that it might be easier to follow for people, who know about raster or vector tiles. 

Can you think of any disadvantage?

**Comment by connormanning** [comment]
Maybe some internal operations would be simpler.  For example during a full-tree traversal, octree-traversal based code like: `for i in range [0, 8): recurse(currentKey + string(i))` is simpler than the analogous operation with DXYZ formatting.  I think in general though, it is simpler to work with DXYZ formatting except for some contrived cases like that, but maybe that is just my own personal preference.

Since both forms contain the exact same information by virtue of being directly convertible to each other, to me the most compelling arguments relate to fitting in with the broader ecosystem, which seems to point toward DXYZ systems.

**Comment by martinheidegger** [comment]
In an numeric-efficiency sense of thinking having `uint8`-fixed amount of children in a tree for a oct representation seems the obvious thing to do. I think it can be changed to a DXYZ system. I am still struggling with the choice because:

Door A: keep Octree in the query would make it easier to port Potree
Door B: use DXYZ would make the future more consistent. _(but be more work now, with possible performance problems in the renderer...)_

@dkastl ?

**Comment by dkastl** [comment]
### Scenario 1:
@connormanning submits a PR to Potree, which gets merged. 

Then we should be able to use EPT with the DXYZ schema and it's all good, even if it would be more work now.

### Scenario 2:
Potree does not merge the PR ... well, not continuing thinking about this for now, but we could use the fork as well.

**Comment by martinheidegger** [comment]
The PR to Potree does not change the structure in potree: it adds a converter to potree which converts from SlippyMap to Potree-style-Octree (like [we would need to do as well](https://github.com/orgs/pnext/projects/1#card-11204535)).

Door A: pnext-viewer - octree<->slippy - pnext-io - ept
Door B: pnext-viewer - pnext-io - <octree<->slippy> - ept
Door B-advanced: pnext-viewer (adapted to use slippy internally) - pnext-io -ept

**Comment by dkastl** [comment]
OK, sorry, but I didn't try to see, what the PR really does.

So in this case, couldn't we just use the same converter to convert from DXYZ to Octree at first?
This should be enough for the proof of concept, and at some point Pnext can drop the converter, when pnext-core is fully implemented?

**Comment by dkastl** [comment]
I would prefer to support the conversion within pnext-io because we don't rely on pull requests to Potree being accepted or not. Especially if the implementation doesn't take too long.

Whether there is an issue with performance or not, time will tell. Better not optimal performance but something working than working too long on theoretically best performing implementation but never get it to a usable state :)

**Comment by martinheidegger** [comment]
> within pnext-io

... which means Door-A?! This means no change on the API structure and we will use/expose the Octree as as is and do the conversion for EPT only.

**Comment by connormanning** [comment]
I believe @m-schuetz is just waiting on my PR to merge my fork into Potree, and from my understanding is willing to merge the EPT loader when it's ready, and it is already pretty much ready to merge.  Markus do you have any thoughts on this discussion?

**Comment by m-schuetz** [comment]
Yeah, I'm going to merge the EPT/Potree branch as soon as you create the PR.

Some things maybe:
* Could you maybe also create an example with EPT in binary format? 
* I didn't have much time to take a close look at the EPT format but from what I've seen it looks fine. As far as I can see, it has all the capabilities of the potree format, + some more. Is that right?
* In entwine.json the schema consists of tuples with name and type. What about adding "bytes" in addition to that? The number of bytes is already implied by the type, but having the number of bytes in addition to that could make it easier for others to write partial but robust EPT loaders. I'd imagine that over time, the EPT format may get additional types and older EPT loaders could simply skip over the bytes of attributes of an unkown type.

**Comment by connormanning** [comment]
Thanks for the input, Markus.  To your questions:

- I will add an EPT binary format example within the next few days 👍
- Yes, I believe that is accurate - I don't think there are any PotreeConverter format features that are missing from EPT
- I've opened connormanning/entwine#109 to discuss the EPT schema specification with your input and some of my own comments

**Comment by hobu** [comment]
For @m-schuetz benefit, Entwine with EPT support is available on windows today via OSGeo4W64, and I have a pull request in progress to add it to Conda Forge (windows and linux) once there is a proper Entwine release with EPT support. If you could suffer OSGeo4W64 for the moment for building your own local trees, that is probably the simplest avenue for testing for you.

**Comment by martinheidegger** [comment]
This issue was resolved with https://github.com/pnext/pnext-io/issues/12#issuecomment-404358628
